// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';
import {
  addDoc,
  deleteDoc,
  doc,
  setDoc,
  updateDoc,
  type CollectionReference,
  type DocumentData,
  type DocumentReference,
  type PartialWithFieldValue,
  type SetOptions,
  type UpdateData,
  type WithFieldValue,
} from 'firebase/firestore';
import { emitFirestorePermissionError } from '../errors';

/**
 * A non-blocking version of the `setDoc` function.
 *
 * This function calls the `setDoc` function to write to the specified document,
 * but it does not return a promise that resolves when the write is complete.
 * Instead, it immediately returns `undefined`. This is useful for fire-and-forget
 * writes, where the application does not need to wait for the write to complete
 * before continuing.
 *
 * If the write fails, the error is caught and a `FirestorePermissionError` is
 * emitted.
 *
 * @param reference The reference to the document to write to.
 * @param data The data to write to the document.
 * @param options An object to configure the set behavior.
 */
export function setDocumentNonBlocking<T>(
  reference: DocumentReference<T>,
  data: WithFieldValue<T>
): void;
export function setDocumentNonBlocking<T>(
  reference: DocumentReference<T>,
  data: PartialWithFieldValue<T>,
  options: SetOptions
): void;
export function setDocumentNonBlocking<T>(
  reference: DocumentReference<T>,
  data: PartialWithFieldValue<T>,
  options?: SetOptions
) {
  const promise = options ? setDoc(reference, data, options) : setDoc(reference, data);
  promise.catch(() => {
    emitFirestorePermissionError({
      operation: 'update',
      path: reference.path,
      data,
    });
  });
}

/**
 * A non-blocking version of the `updateDoc` function.
 *
 * This function calls the `updateDoc` function to update the specified document,
 * but it does not return a promise that resolves when the update is complete.
 * Instead, it immediately returns `undefined`. This is useful for fire-and-forget
 * updates, where the application does not need to wait for the update to complete
 * before continuing.
 *
 * If the update fails, the error is caught and a `FirestorePermissionError` is
 * emitted.
 *
 * @param reference The reference to the document to update.
 * @param data An object containing the fields and values with which to update the document.
 */
export function updateDocumentNonBlocking<T = DocumentData>(
  reference: DocumentReference<T>,
  data: UpdateData<T>
): void {
  updateDoc(reference, data).catch(() => {
    emitFirestorePermissionError({
      operation: 'update',
      path: reference.path,
      data,
    });
  });
}

/**
 * A non-blocking version of the `addDoc` function.
 *
 * This function calls the `addDoc` function to add a new document to the specified
 * collection, but it does not return a promise that resolves with the new document's
 * reference. Instead, it immediately returns `undefined`. This is useful for
 * fire-and-forget writes, where the application does not need to know the ID of
 * the new document.
 *
 * If the write fails, the error is caught and a `FirestorePermissionError` is
 * emitted.
 *
 * @param reference The reference to the collection to add the document to.
 * @param data The data for the new document.
 * @returns The `DocumentReference` of the newly created document.
 */
export function addDocumentNonBlocking<T>(
  reference: CollectionReference<T>,
  data: WithFieldValue<T>
): void {
  addDoc(reference, data).catch(() => {
    emitFirestorePermissionError({
      operation: 'create',
      path: reference.path,
      data,
    });
  });
}

/**
 * A non-blocking version of the `deleteDoc` function.
 *
 * This function calls the `deleteDoc` function to delete the specified document,
 * but it does not return a promise that resolves when the delete is complete.
 * Instead, it immediately returns `undefined`. This is useful for fire-and-forget
 * deletes, where the application does not need to wait for the delete to complete
 * before continuing.
 *
 * If the delete fails, the error is caught and a `FirestorePermissionError` is
 * emitted.
 *
 * @param path The path to the document to delete.
 * @param id The ID of the document to delete.
 */
export function deleteDocumentNonBlocking(path: string, id: string): void {
  const reference = doc(db, path, id);
  deleteDoc(reference).catch(() => {
    emitFirestorePermissionError({
      operation: 'delete',
      path: reference.path,
    });
  });
}
