
// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';

import {
  onSnapshot,
  type DocumentReference,
  type DocumentData,
} from 'firebase/firestore';
import { useEffect, useState, useMemo } from 'react';
import { FirestorePermissionError } from '../errors';
import { errorEmitter } from '../events';
import { useFirebase } from '../hooks';

interface UseDocumentOptions<T> {
  onError?: (error: any) => void;
  onData?: (data: T | null) => void;
}

interface UseDocumentResult<T> {
  data: T | null;
  error: any;
  isLoading: boolean;
}

/**
 * A React hook that subscribes to a Firestore document and returns the data,
 * loading state, and error.
 *
 * This hook is designed to be used with Firestore document references. It
 * will automatically unsubscribe from the document when the component unmounts.
 * It will also automatically re-subscribe to the document if the reference changes.
 *
 * This hook will also automatically handle permission errors and emit them
 * to the global error emitter.
 *
 * @param docRef The Firestore document reference to subscribe to.
 * @param options An object to configure the hook's behavior.
 * @returns An object containing the data, error, and loading state.
 */
export function useDocument<T = DocumentData>(
  docRef: DocumentReference<T> | null,
  options?: UseDocumentOptions<T>
): UseDocumentResult<T> {
  const { firestore } = useFirebase();
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState<unknown>(null);
  const isLoading = data === null && error === null;

  // Memoize the docRef to prevent re-subscribing on every render if the path is the same.
  const memoizedDocRef = useMemo(() => docRef, [docRef?.path]);

  useEffect(() => {
    if (!memoizedDocRef) {
      setData(null);
      setError(null);
      return;
    }

    const unsubscribe = onSnapshot(
      memoizedDocRef,
      (snapshot) => {
        if (snapshot.exists()) {
          const docData = { id: snapshot.id, ...snapshot.data() } as T;
          setData(docData);
          setError(null);
          options?.onData?.(docData);
        } else {
          setData(null);
          setError(null);
          options?.onData?.(null);
        }
      },
      (error) => {
        const isPermissionError = error.code === 'permission-denied';
        if (isPermissionError) {
          const contextualError = new FirestorePermissionError({
            operation: 'get',
            path: memoizedDocRef.path,
          });
          errorEmitter.emit('permission-error', contextualError);
        }

        setError(error);
        setData(null);
        options?.onError?.(error);
      }
    );

    return unsubscribe;
  }, [firestore, memoizedDocRef, options]);

  return { data, error, isLoading };
}
