
// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';

import {
  onSnapshot,
  queryEqual,
  type CollectionReference,
  type DocumentData,
  type Query,
} from 'firebase/firestore';
import { useEffect, useMemo, useRef, useState } from 'react';
import { FirestorePermissionError } from '../errors';
import { errorEmitter } from '../events';
import { useFirebase } from '../hooks';

interface UseCollectionOptions<T> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  onError?: (error: any) => void;
  onData?: (data: T[]) => void;
}

interface UseCollectionResult<T> {
  data: T[] | null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  error: any;
  isLoading: boolean;
}

/**
 * A React hook that subscribes to a Firestore collection and returns the data,
 * loading state, and error.
 *
 * This hook is designed to be used with Firestore queries and collections. It
 * will automatically unsubscribe from the query when the component unmounts.
 * It will also automatically re-subscribe to the query if the query changes.
 *
 * This hook will also automatically handle permission errors and emit them
 * to the global error emitter.
 *
 * @param targetRefOrQuery The Firestore query or collection to subscribe to.
 * @param options An object to configure the hook's behavior.
 * @returns An object containing the data, error, and loading state.
 */
export function useCollection<T = DocumentData>(
  targetRefOrQuery: CollectionReference<T> | Query<T> | null,
  options?: UseCollectionOptions<T>
): UseCollectionResult<T> {
  const { firestore } = useFirebase();
  const [data, setData] = useState<T[] | null>(null);
  const [error, setError] = useState<unknown>(null);
  const isLoading = data === null && error === null;

  // Memoize the query to prevent re-subscribing on every render.
  const memoizedTargetRefOrQuery = useMemo(
    () => targetRefOrQuery,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [targetRefOrQuery ? queryEqual(targetRefOrQuery, targetRefOrQuery) : null]
  );

  // We need to store the previous query to unsubscribe from it when the query
  // changes.
  const prevTargetRefOrQuery = useRef<typeof memoizedTargetRefOrQuery | null>(null);

  useEffect(() => {
    // If the query is null, there is nothing to subscribe to.
    if (!memoizedTargetRefOrQuery) {
      setData(null);
      setError(null);
      return;
    }

    // If the query has not changed, there is no need to re-subscribe.
    if (
      prevTargetRefOrQuery.current &&
      queryEqual(prevTargetRefOrQuery.current, memoizedTargetRefOrQuery)
    ) {
      return;
    }

    prevTargetRefOrQuery.current = memoizedTargetRefOrQuery;
    const unsubscribe = onSnapshot(
      memoizedTargetRefOrQuery,
      (snapshot) => {
        const data = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }));
        setData(data);
        setError(null);
        options?.onData?.(data);
      },
      (error) => {
        const isPermissionError = error.code === 'permission-denied';
        if (isPermissionError) {
          // Firebase does not include the path in the error object, so we have
          // to get it from the query object. This is a bit of a hack, but it
          // works.
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const internalQuery = memoizedTargetRefOrQuery as any;
          const path = internalQuery.path ?? internalQuery._query.path.canonicalString();

          const contextualError = new FirestorePermissionError({
            operation: 'list',
            path,
          });
          errorEmitter.emit('permission-error', contextualError);
        }

        setError(error);
        setData(null);
        options?.onError?.(error);
      }
    );

    return unsubscribe;
  }, [firestore, memoizedTargetRefOrQuery, options]);

  return { data, error, isLoading };
}
