
// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';

import { FirebaseProvider } from './provider';

/**
 * A client-side component that initializes the Firebase SDK.
 *
 * This component should be used at the root of your application to ensure that
 * Firebase is available on all pages.
 */
export function FirebaseClientProvider({ children }: { children: React.ReactNode }) {
  return <FirebaseProvider>{children}</FirebaseProvider>;
}
