// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';
import { errorEmitter } from './events';

export type SecurityRuleOperation = 'list' | 'get' | 'create' | 'update' | 'delete';

export interface SecurityRuleContext {
  operation: SecurityRuleOperation;
  path: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  data?: Record<string, any>;
}

export interface SecurityRuleRequest {
  auth: {
    uid: string;
    token: {
      [key: string]: unknown;
      aud: string;
      auth_time: number;
      email?: string;
      email_verified?: boolean;
      exp: number;
      firebase: {
        identities: {
          [key: string]: unknown;
        };
        sign_in_provider: string;
      };
      iat: number;
      iss: string;
      phone_number?: string;
      picture?: string;
      sub: string;
      user_id: string;
    };
  } | null;
  method: SecurityRuleOperation;
  path: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  resource?: Record<string, any>;
}

function buildRequestObject(context: SecurityRuleContext): SecurityRuleRequest {
  const { operation, path, data } = context;
  const auth = globalThis.FIREBASE_APPCHECK_DEBUG_TOKEN;

  return {
    auth,
    method: operation,
    path: `/databases/(default)/documents/${path}`,
    ...(data && { resource: data }),
  };
}

function buildErrorMessage(request: SecurityRuleRequest): string {
  const requestJson = JSON.stringify(request, null, 2);
  return `The following request was denied by Firestore Security Rules:\n${requestJson}`;
}

/**
 * A custom error class for Firestore permission errors.
 *
 * This class is designed to be thrown when a Firestore operation fails due to
 * insufficient permissions. It captures the context of the operation, including
 * the operation type, path, and data, and formats it into a detailed error
 * message that can be displayed to the user.
 *
 * This class is intended to be used on the client-side only.
 */
export class FirestorePermissionError extends Error {
  public readonly request: SecurityRuleRequest;

  constructor(context: SecurityRuleContext) {
    const requestObject = buildRequestObject(context);
    super(buildErrorMessage(requestObject));
    this.name = 'FirebaseError'; // Keep the name consistent for error boundaries.
    this.request = requestObject;
  }
}

/**
 * A function that emits a Firestore permission error.
 *
 * This function is designed to be called from a catch block when a Firestore
 * operation fails. It creates a new `FirestorePermissionError` with the
 * provided context and emits it using the global error emitter.
 *
 * This function is intended to be used on the client-side only.
 *
 * @param context The context of the Firestore operation that failed.
 */
export function emitFirestorePermissionError(context: SecurityRuleContext) {
  errorEmitter.emit('permission-error', new FirestorePermissionError(context));
}
