
// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';

import { EventEmitter } from 'eventemitter3';
import type { FirestorePermissionError } from './errors';

interface ErrorEvents {
  'permission-error': (error: FirestorePermissionError) => void;
}

export const errorEmitter = new EventEmitter<ErrorEvents>();
