// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';
import { useContext, useMemo } from 'react';
import { FirebaseContext, type FirebaseContextValue } from './context';
import { useSyncExternalStore } from 'use-sync-external-store/shim';
import { getAuth, onIdTokenChanged, type User } from 'firebase/auth';

/**
 * A React hook that returns the Firebase context.
 *
 * This hook is designed to be used by other hooks and components that need
 * access to the Firebase SDK. It is not intended to be used directly by
 * application code.
 *
 * @returns The Firebase context.
 * @throws An error if the hook is used outside of a `FirebaseProvider`.
 * @internal
 */
export function useFirebase(): FirebaseContextValue {
  const context = useContext(FirebaseContext);
  if (context === undefined) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
}

/**
 * The result of the `useUser` hook.
 */
export interface UseUserResult {
  /**
   * The currently signed-in user, or `null` if no user is signed in.
   */
  readonly user: User | null;
  /**
   * `true` if the user is currently being loaded, and `false` otherwise.
   *
   * This is useful for showing a loading indicator while the user is being
   * authenticated.
   */
  readonly isUserLoading: boolean;
}

/**
 * A React hook that returns the currently signed-in user.
 *
 * This hook subscribes to the authentication state of the application and
 * returns the currently signed-in user. If no user is signed in, it returns
 * `null`.
 *
 * This hook is designed to be used in components that need to access the
 * current user's information, such as displaying the user's name and profile
 * picture.
 *
 * @returns An object containing the current user and a loading state.
 */
export function useUser(): UseUserResult {
  const { auth } = useFirebase();

  const user = useSyncExternalStore(
    (callback) => onIdTokenChanged(auth, callback),
    () => auth.currentUser,
    () => null
  );

  return {
    user,
    isUserLoading: user === undefined,
  };
}

/**
 * A React hook that returns the Firestore instance.
 * @returns The Firestore instance.
 */
export function useFirestore() {
  const { firestore } = useFirebase();
  return firestore;
}

/**
 * A React hook that returns a memoized value that is safe to use in a
 * dependency array.
 *
 * This hook is useful for memoizing values that are not safe to use in a
 * dependency array, such as objects and arrays. It works by serializing the
 * value to a JSON string and using that as the dependency.
 *
 * @param factory A function that returns the value to memoize.
 * @param deps The dependencies of the factory function.
 * @returns The memoized value.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function useMemoFirebase<T>(factory: () => T, deps: any[]): T {
  // eslint-disable-next-line react-hooks/exhaustive-deps
  return useMemo(factory, [JSON.stringify(deps)]);
}
