
// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
'use client';

import { app, auth, db } from '@/app/lib/firebase';
import { useEffect, useState } from 'react';
import { FirebaseContext, FirebaseContextValue } from './context';
import { errorEmitter } from './events';
import { FirestorePermissionError } from './errors';
import { Auth, onIdTokenChanged, type IdTokenResult } from 'firebase/auth';
import { setCookie, destroyCookie } from 'nookies';

const FIREBASE_AUTH_COOKIE = '__session';

async function setSessionCookie(token: string | null) {
  if (token) {
    setCookie(null, FIREBASE_AUTH_COOKIE, token, {
      maxAge: 60 * 60, // 1 hour
      path: '/',
      secure: true,
      sameSite: 'strict',
    });
  } else {
    destroyCookie(null, FIREBASE_AUTH_COOKIE);
  }
}

function useFirebaseAuth(auth: Auth) {
  useEffect(() => {
    return onIdTokenChanged(auth, async (user) => {
      if (user) {
        const token = await user.getIdToken();
        await setSessionCookie(token);
      } else {
        await setSessionCookie(null);
      }
    });
  }, [auth]);
}

/**
 * A component that provides the Firebase context to its children.
 *
 * This component is responsible for initializing the Firebase SDK and providing
 * the Firebase context to its children. It also handles authentication and
 * displays a permission error overlay when a Firestore permission error occurs.
 *
 * This component should be used at the root of your application to ensure that
 * Firebase is available on all pages.
 */
export function FirebaseProvider({ children }: { children: React.ReactNode }) {
  const [permissionError, setPermissionError] = useState<FirestorePermissionError | null>(null);

  useFirebaseAuth(auth);

  useEffect(() => {
    const handlePermissionError = (error: FirestorePermissionError) => {
      setPermissionError(error);
    };

    errorEmitter.on('permission-error', handlePermissionError);

    return () => {
      errorEmitter.off('permission-error', handlePermissionError);
    };
  }, []);

  const context: FirebaseContextValue = {
    app,
    auth,
    firestore: db,
  };

  if (permissionError) {
    const request = JSON.stringify(permissionError.request, null, 2);
    // This is a temporary error screen that will be replaced by a more
    // user-friendly one in the future.
    return (
      <div
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          zIndex: 9999,
          color: 'white',
        }}
      >
        <div
          style={{
            backgroundColor: '#222',
            padding: '2rem',
            borderRadius: '0.5rem',
            maxWidth: '80%',
            maxHeight: '80%',
            overflow: 'auto',
          }}
        >
          <h1>Permission Error</h1>
          <p>
            The following request was denied by Firestore Security Rules. Please update your rules
            to allow this request.
          </p>
          <pre>{request}</pre>
          <button
            onClick={() => {
              setPermissionError(null);
            }}
          >
            Dismiss
          </button>
        </div>
      </div>
    );
  }

  return <FirebaseContext.Provider value={context}>{children}</FirebaseContext.Provider>;
}
