
// This file was autogenerated by Firebase Studio.
// Do not edit this file manually.
import { initializeApp, getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

const firebaseConfig = {
  apiKey: 'AIzaSyBHWld1vQcm_cnfYGmd3Nz0COppTheVtGw',
  authDomain: 'studio-3883937532-b7f00.firebaseapp.com',
  projectId: 'studio-3883937532-b7f00',
  storageBucket: 'studio-3883937532-b7f00.appspot.com',
  messagingSenderId: '653581985755',
  appId: '1:653581985755:web:e57973f0b7a6f2436fe9fe',
  measurementId: 'G-58GYN4ZKBZ',
};

// Initialize Firebase
const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export { app, auth, db, storage };
